/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./StorageOutpost.types";
import * as _1 from "./StorageOutpost.client";
import * as _2 from "./StorageOutpost.recoil";
export namespace contracts {
  export const StorageOutpost = { ..._0,
    ..._1,
    ..._2
  };
}