/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  storage_outpost_code_id: number;
}
export type ExecuteMsg = {
  create_outpost: {
    channel_open_init_options: ChannelOpenInitOptions;
  };
} | {
  map_user_outpost: {
    outpost_owner: string;
  };
};
export type TxEncoding = "proto3" | "proto3json";
export interface ChannelOpenInitOptions {
  connection_id: string;
  counterparty_connection_id: string;
  counterparty_port_id?: string | null;
  tx_encoding?: TxEncoding | null;
}
export type QueryMsg = {
  get_contract_state: {};
} | {
  get_user_outpost_address: {
    user_address: string;
  };
};
export interface ContractState {
  storage_outpost_code_id: number;
}
export type String = string;